language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r src/requirements/base.txt
script:
    python src/manage.py collectstatic &&
    python src/manage.py test