version: '3.7'
services:
  django:
    build:
        context: ./docker/django
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
      - backend-data:/usr/lib/python3/dist-packages
    working_dir: /usr/src/app
    environment:
        - PYTHONUNBUFFERED=1
        - DJANGO_KEY=${DJANGO_KEY}
        - DJANGO_DB_NAME=${POSTGRES_DB}
        - DJANGO_DB_USER=${POSTGRES_USER}
        - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}

  bdd:
    build:
        context: ./docker/postgresql
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./:/usr/src/app
      - bdd-data:/var/lib/postgresql/data
    working_dir: /usr/src/app
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
    backend-data:
    bdd-data:

