# Generated by Django 3.0.4 on 2020-05-04 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=400)),
                ('code', models.CharField(max_length=30)),
                ('img_url', models.CharField(blank=True, max_length=400, null=True)),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('salt', models.CharField(blank=True, max_length=10, null=True)),
                ('fat', models.CharField(blank=True, max_length=10, null=True)),
                ('sugars', models.CharField(blank=True, max_length=10, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=10, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=400, null=True)),
                ('allergens', models.CharField(blank=True, max_length=400, null=True)),
                ('nutrition_grades', models.CharField(max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Category')),
            ],
        ),
        migrations.CreateModel(
            name='BackupProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
