# Generated by Django 3.0.4 on 2020-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupproduct',
            name='category_name',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
